# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jonathan Gardiner
description: I'm Jonathan, I'm a full-stack develope currently based in London.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol fo your site
twitter_username: thejongardiner
github_username:  jelgar1

# Build settings
markdown: kramdown
